title: Blog - Charles Gabouleaud
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://charlesgabouleaud.github.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 3

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: charlesgabouleaud
   twitter: chgabouleaud
#   facebook: brianmaierjr
   email: charles.gabouleaud@gmail.com

google_analytics: "UA-58263416-1"
