title: Blog - Charles Gabouleaud
description: Blog personnel de Charles gabouleaud

url: http://charlesgabouleaud.github.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 10

navigation:
 - title: Accueil
   url: /index.html
 - title: A propos
   url: /about
 - title: Contact
   url: /contact

social:
   github: charlesgabouleaud
   twitter: chgabouleaud
   email: charles.gabouleaud@gmail.com
   linkedin: charlesgabouleaud

google_analytics: "UA-83608468-1"
